name: Tudo e publicar o requirements com docker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "PROD" branch
  push:
    branches: [ "PROD" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Configurando para utilizar o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Baixando os arquivos
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          pip install -r requirements.txt
          
      - name: Testando o arquivo
        run: coverage run rpa.py

      - name: Mostrando os resultados
        run: coverage report

      - name: Logando no docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Verificando se a conta está logada
        run: docker info
      
      - name: Criando uma imagem no docker
        run: docker build -t sarahdemoraes/rpa:${{github.run_number}}
        
      - name: Criando uma imagem no docker
        run: docker push sarahdemoraes/rpa:${{github.run_number}}

      
